# Generated by Django 3.1.7 on 2023-02-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230212_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraData',
        ),
    ]
